#!/bin/bash
# Init the LIDAR as silent
#
### BEGIN INIT INFO
# Provides:          lidar
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Should-Start:      autofs
# Should-Stop:       autofs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Init the LIDAR as silent
# Description:       Init the LIDAR as silent 
### END INIT INFO

if [ ! -L /sys/class/gpio/gpio18 ]; then
        sudo /bin/sh -c "echo 18 > /sys/class/gpio/export"
        sudo chmod 777 /sys/class/gpio/gpio18/direction
        echo "out" > /sys/class/gpio/gpio18/direction
        sudo chmod 777 /sys/class/gpio/gpio18/value
        echo 0 > /sys/class/gpio/gpio18/value
fi   

if [ ! -L /usr/bin/lidar ]; then
        sudo ln -s /etc/init.d/lidar /usr/bin/lidar
fi   

case "$1" in
start)  echo 1 > /sys/class/gpio/gpio18/value
        ;;
stop)   echo 0 > /sys/class/gpio/gpio18/value
        ;;
esac
exit 0